---
title: "Seminario de Ciencia de Datos"
format:
  html:
    theme: darkly
    css: styles.css
---

## Presentaciones y Notas


### Clase 1: Arranque
* [Arranque](presentaciones/1-inicio-y-setup.html)
* [Presentación Aleksander Dietrichson](presentacion.html)

### Clase 2: Admin y R
* [Admin y R](presentaciones/2-sincronizar-repositorios-primer-codigo-y-analysis.html)
* [Primer análisis Indec](Primer-analysis.html)

### Clase 3: Revisión de la teoría
* [Revisión de la teoría](presentaciones/3-centralizacion-y-dispersión.html)
* [Notas de la clase 2025-04-14](notas-de-la-clase-2025-04-14.html)

### Clase 4: Método científico. Manipulación de datos.
* [Método científico. Manipulación de datos.](presentaciones/4-metodo-científico.html)
* [Notas de la clase 2025-04-21](notas-de-la-clase-2025-04-21.html)

### Clase 5: La prueba de $\chi^2$
* [La prueba de $\chi^2$](presentaciones/5-chi-cuadrado.html)
* [Notas de la clase 2025-04-28](notas-de-la-clase-2025-04-28-II.html)
* [Notas de la clase 2025-04-28](notas-de-la-clase-2025-04-28.html)
* [Notas de la clase 2025-05-05](notas-de-la-clase-2025-05-05.html)

### Clase 7: Pruebas de independencia
* [Pruebas de independencia](presentaciones/7-pruebas-de-independencia.html)
